# -*- coding: utf-8 -*-
"""Univariate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10hBjcKhJV_ahtSJPVicHyrX0pIa6xkdd
"""



from pathlib import Path

import pandas as pd

try:
    from IPython.display import display
except ImportError:
    display = print

PROJECT_ROOT = Path(__file__).resolve().parents[1]
RAW_DISCHARGE = PROJECT_ROOT / "data" / "raw" / "Ukai(1975-2021).xlsx"

df = pd.read_excel(RAW_DISCHARGE, sheet_name="62255")

Q = df.iloc[:, 3].dropna()

q965 = Q.quantile(0.9915)

print("96.5th percentile =", q965)

import pandas as pd

df = pd.read_excel(RAW_DISCHARGE)
df["Date"] = pd.to_datetime(
    df[["Year", "Month", "Day"]]
)

print(df.head())

# Basic information
print(df.info())

# First few observations
display(df.head())

# Last few observations
display(df.tail())

# Check missing values
print("\nMissing values:")
print(df.isnull().sum())

# Check duplicate rows
print("Duplicate rows:", df.duplicated().sum())

# Basic statistics of discharge
print("\nDischarge statistics:")
print(df["Q(m3/s)"].describe())

# Number of observations in each year
year_counts = df.groupby("Year").size()

display(year_counts)

print("Minimum observations in a year:", year_counts.min())
print("Maximum observations in a year:", year_counts.max())

print("Number of years:", df["Year"].nunique())

print("Years present:")
print(sorted(df["Year"].unique()))

annual_max = (
    df.groupby("Year")["Q(m3/s)"]
      .max()
      .reset_index()
)

annual_max.columns = ["Year", "Peak"]

display(annual_max)

threshold = 4622.9

exceed = df[df["Q(m3/s)"] > threshold].copy()

print("Threshold:", threshold, "m³/s")
print("Number of exceedances:", len(exceed))

print(exceed[["Date", "Q(m3/s)"]].head(20))

import pandas as pd

# Make sure dates are datetime
exceed['Date'] = pd.to_datetime(exceed['Date'])

# Sort chronologically
exceed = exceed.sort_values('Date').reset_index(drop=True)

# Minimum separation between independent flood peaks
# Use the same interval used by the SFE-IFC procedure
interval = 15;

independent = []

for i in range(len(exceed)):

    # First exceedance is automatically considered
    # as the first independent event
    if len(independent) == 0:
        independent.append(i)
        continue

    last_idx = independent[-1]

    # Number of days since the previously selected peak
    gap = (exceed.loc[i, 'Date'] -
           exceed.loc[last_idx, 'Date']).days

    if gap >= interval:
        # New independent event
        independent.append(i)

    else:
        # Same flood event → retain the larger peak
        if exceed.loc[i, 'Q(m3/s)'] > exceed.loc[last_idx, 'Q(m3/s)']:
            independent[-1] = i

independent_exceed = exceed.loc[independent].reset_index(drop=True)

print("Total exceedances:", len(exceed))
print("Independent flood events:", len(independent_exceed))

print(independent_exceed)

ams = annual_max["Peak"].dropna().reset_index(drop=True)

print("Number of AMS observations:", len(ams))
print(ams.describe())

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))

plt.hist(ams, bins=10, edgecolor="black")

plt.xlabel("Peak Discharge (m³/s)")
plt.ylabel("Frequency")
plt.title("Histogram of AMS Peak Discharge")

plt.show()

plt.figure(figsize=(8, 4))

plt.boxplot(ams, vert=False)

plt.xlabel("Peak Discharge (m³/s)")
plt.title("Boxplot of AMS Peak Discharge")

plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy import stats

# ============================================================
# 2. EMPIRICAL CDF
# ============================================================

ams_sorted = np.sort(ams)

n = len(ams_sorted)

# Weibull plotting position
empirical_cdf = np.arange(1, n + 1) / (n + 1)


# ============================================================
# 3. CANDIDATE DISTRIBUTIONS
# ============================================================

distributions = {
    "GEV": stats.genextreme,
    "Gumbel": stats.gumbel_r,
    "Lognormal": stats.lognorm,
    "Gamma": stats.gamma,
    "Weibull": stats.weibull_min,
    "Pearson III": stats.pearson3
}


# ============================================================
# 4. FIT DISTRIBUTIONS
# ============================================================

fitted_params = {}

for name, distribution in distributions.items():

    try:
        params = distribution.fit(ams)
        fitted_params[name] = params

        print(f"\n{name}")
        print("Parameters:", params)

    except Exception as e:
        print(f"{name} could not be fitted: {e}")


# ============================================================
# 5. PLOT EMPIRICAL CDF + THEORETICAL CDFS
# ============================================================

plt.figure(figsize=(10, 6))

# Empirical CDF
plt.plot(
    ams_sorted,
    empirical_cdf,
    "ko",
    markersize=5,
    label="Empirical CDF"
)


# Theoretical CDFs
x = np.linspace(
    ams_sorted.min(),
    ams_sorted.max(),
    500
)

for name, distribution in distributions.items():

    if name in fitted_params:

        params = fitted_params[name]

        cdf = distribution.cdf(x, *params)

        plt.plot(
            x,
            cdf,
            linewidth=2,
            label=name
        )


plt.xlabel("Annual Maximum Discharge (m³/s)")
plt.ylabel("Cumulative Probability")
plt.title("AMS: Empirical CDF vs Candidate Distributions")

plt.grid(True, alpha=0.3)
plt.legend()

plt.show()

# ============================================================
# 6. AIC AND BIC
# ============================================================

results = []

for name, distribution in distributions.items():

    if name not in fitted_params:
        continue

    params = fitted_params[name]

    # log-likelihood
    loglik = np.sum(distribution.logpdf(ams, *params))

    # number of parameters
    k = len(params)

    # AIC
    aic = 2 * k - 2 * loglik

    # BIC
    bic = k * np.log(len(ams)) - 2 * loglik

    results.append({
        "Distribution": name,
        "LogLikelihood": loglik,
        "AIC": aic,
        "BIC": bic
    })


results_df = pd.DataFrame(results)

results_df = results_df.sort_values("AIC")

print("\nDistribution comparison:")
print(results_df)

# ============================================================
# 7. KOLMOGOROV-SMIRNOV TEST
# ============================================================

ks_results = []

for name, distribution in distributions.items():

    if name not in fitted_params:
        continue

    params = fitted_params[name]

    ks_stat, ks_pvalue = stats.kstest(
        ams,
        distribution.cdf,
        args=params
    )

    ks_results.append({
        "Distribution": name,
        "KS Statistic": ks_stat,
        "KS p-value": ks_pvalue
    })


ks_df = pd.DataFrame(ks_results)

ks_df = ks_df.sort_values("KS Statistic")

print("\nKS goodness-of-fit:")
print(ks_df)

comparison = results_df.merge(
    ks_df,
    on="Distribution"
)

comparison = comparison.sort_values("AIC")

print(comparison)

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

# --------------------------------------------------
# 1. AMS data
# --------------------------------------------------
data = np.asarray(ams)
data = data[np.isfinite(data)]
data = data[data > 0]       # Lognormal requires positive values

# --------------------------------------------------
# 2. Fit Lognormal distribution
# --------------------------------------------------
shape, loc, scale = stats.lognorm.fit(data, floc=0)

# --------------------------------------------------
# 3. Calculate theoretical quantiles
# --------------------------------------------------
n = len(data)

# Empirical plotting positions
p = (np.arange(1, n + 1) - 0.5) / n

# Observed quantiles
observed = np.sort(data)

# Theoretical Lognormal quantiles
theoretical = stats.lognorm.ppf(
    p,
    s=shape,
    loc=loc,
    scale=scale
)

# --------------------------------------------------
# 4. QQ Plot
# --------------------------------------------------
plt.figure(figsize=(7, 6))

plt.scatter(theoretical, observed, s=35)

# 1:1 reference line
min_val = min(theoretical.min(), observed.min())
max_val = max(theoretical.max(), observed.max())

plt.plot(
    [min_val, max_val],
    [min_val, max_val],
    'r--',
    linewidth=2
)

plt.xlabel("Theoretical Lognormal Quantiles")
plt.ylabel("Observed AMS Peak Discharges (m³/s)")
plt.title("Q-Q Plot: AMS vs Lognormal Distribution")

plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

"""The Lognormal distribution was selected as the marginal distribution for the AMS peak-discharge series because it provided the best overall fit among the candidate distributions, having the lowest AIC and BIC, the lowest KS statistic, and the highest KS p-value. The Q-Q plot further showed that the observed AMS quantiles were generally in good agreement with the theoretical Lognormal quantiles, although some deviation was observed in the upper tail."""

from scipy.stats import lognorm

given_discharge = 4622.9

# Parameters obtained earlier from your AMS Lognormal fit
p_non_exceedance = lognorm.cdf(
    given_discharge,
    s=shape,
    loc=loc,
    scale=scale
)

p_exceedance = 1 - p_non_exceedance

return_period = 1 / p_exceedance

print(f"Threshold discharge = {given_discharge:.2f} m³/s")
print(f"Non-exceedance probability = {p_non_exceedance:.6f}")
print(f"Exceedance probability = {p_exceedance:.6f}")
print(f"Return period = {return_period:.2f} years")

"""# univariate POT analysis"""

pot_excess = independent_exceed["Q(m3/s)"] - threshold
pot_q = independent_exceed["Q(m3/s)"].values

# Excess above threshold
pot_excess = pot_q - threshold

print("Number of independent POT events:", len(pot_excess))
print("Minimum excess:", pot_excess.min())
print("Maximum excess:", pot_excess.max())

# Check that all are actually above the threshold
print("All exceed threshold:", np.all(pot_q > threshold))

plt.figure(figsize=(8, 5))

plt.hist(pot_excess, bins=10, density=True, edgecolor="black")

plt.xlabel("Excess discharge, Q - u (m³/s)")
plt.ylabel("Density")
plt.title("POT Excess Discharge Distribution")

plt.show()

from scipy.stats import expon, gamma, lognorm, weibull_min, genpareto

distributions = {
    "Exponential": expon,
    "Gamma": gamma,
    "Lognormal": lognorm,
    "Weibull": weibull_min,
    "Generalized Pareto": genpareto
}

results = []

for name, dist in distributions.items():

    # Fit distribution
    params = dist.fit(pot_excess)

    # Log-likelihood
    loglik = np.sum(dist.logpdf(pot_excess, *params))

    # Number of parameters
    k = len(params)

    # AIC
    aic = 2*k - 2*loglik

    # BIC
    bic = k*np.log(len(pot_excess)) - 2*loglik

    # KS test
    ks_stat, ks_p = __import__("scipy").stats.kstest(
        pot_excess,
        dist.cdf,
        args=params
    )

    results.append([
        name,
        loglik,
        aic,
        bic,
        ks_stat,
        ks_p
    ])

results_df = pd.DataFrame(
    results,
    columns=[
        "Distribution",
        "LogLikelihood",
        "AIC",
        "BIC",
        "KS Statistic",
        "KS p-value"
    ]
)

results_df = results_df.sort_values("AIC")

print(results_df.to_string(index=False))

from scipy.stats import rankdata

# Sort excesses
x = np.sort(pot_excess)

# Empirical CDF
n = len(x)
empirical_cdf = np.arange(1, n + 1) / n

plt.figure(figsize=(9, 6))

# Empirical CDF
plt.step(
    x,
    empirical_cdf,
    where="post",
    label="Empirical CDF",
    linewidth=2
)

# Fitted distributions
for name, dist in distributions.items():

    params = dist.fit(pot_excess)

    theoretical_cdf = dist.cdf(x, *params)

    plt.plot(
        x,
        theoretical_cdf,
        label=name
    )

plt.xlabel("Excess discharge, Q - u (m³/s)")
plt.ylabel("Cumulative Probability")
plt.title("POT Excess: Empirical CDF vs Fitted Distributions")
plt.legend()
plt.grid(alpha=0.3)

plt.show()

fig, axes = plt.subplots(2, 3, figsize=(14, 9))
axes = axes.flatten()

for i, (name, dist) in enumerate(distributions.items()):

    params = dist.fit(pot_excess)

    # Theoretical probabilities
    p = (np.arange(1, n + 1) - 0.5) / n

    # Theoretical quantiles
    theoretical_q = dist.ppf(p, *params)

    # Observed quantiles
    observed_q = np.sort(pot_excess)

    axes[i].scatter(
        theoretical_q,
        observed_q,
        s=25
    )

    # 45-degree reference line
    min_val = min(theoretical_q.min(), observed_q.min())
    max_val = max(theoretical_q.max(), observed_q.max())

    axes[i].plot(
        [min_val, max_val],
        [min_val, max_val],
        linestyle="--"
    )

    axes[i].set_title(name)
    axes[i].set_xlabel("Theoretical Quantiles")
    axes[i].set_ylabel("Observed Quantiles")
    axes[i].grid(alpha=0.3)

# Hide unused sixth subplot
axes[-1].axis("off")

plt.tight_layout()
plt.show()

"""Gamma produced the lowest AIC and BIC among the candidate distributions. However, the GPD provided a comparable goodness-of-fit and Q–Q performance and is theoretically justified for POT threshold exceedances. The estimated GPD shape parameter was 0.000129, which is effectively zero, indicating that the excess distribution is approximately exponential.

"Among the candidate distributions, the Gamma distribution yielded the lowest AIC and BIC, indicating the best statistical fit according to information criteria. However, the Generalized Pareto distribution provided a comparable Q–Q fit and is theoretically appropriate for modeling threshold exceedances under the POT framework. The fitted GPD had a shape parameter close to zero, indicating behavior close to the exponential distribution."
"""

from scipy.stats import genpareto

gpd_params = genpareto.fit(pot_excess)

print("GPD parameters:")
print("Shape (xi) =", gpd_params[0])
print("Location =", gpd_params[1])
print("Scale =", gpd_params[2])

"""<h1> Bivariate Analysis</h1>


"""

